name: RELEASE
on:
  push:
    tags:
      - 'v*'
jobs:
  Pre_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create GitHub release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG=$(git describe --tags --abbrev=0)
          gh release create $TAG --draft --title $TAG

  Build_release:
    needs: Pre_release
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-11]
    runs-on: ${{ matrix.os }}

    # Required to upload release artifacts to GitHub
    permissions:
      contents: write

    steps:
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17.0.7'
          distribution: 'graalvm'

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build release
        run: mvn clean package -DskipTests -T 3

      - name: Upload artifacts for MacOS
        uses: actions/upload-artifact@v3
        if: ${{startsWith(github.ref, 'refs/tags/') && runner.os == 'macOS' }}
        with:
          name: zdb_mac
          path: cli/target/zdb

#      - name: Upload artifacts for Windows
#        uses: actions/upload-artifact@v3
#        if: ${{startsWith(github.ref, 'refs/tags/') && runner.os == 'Windows' }}
#        with:
#          draft: zdb_linux
#          path: cli/target/zdb

      - name: Upload artifacts for Linux
        uses: actions/upload-artifact@v3
        if: ${{startsWith(github.ref, 'refs/tags/') && runner.os == 'Linux' }}
        with:
          draft: false
          path: cli/target/zdb
